image:
- Visual Studio 2017
build: on

clone_folder: c:\gopath\src\github.com\adedayo\tcpscan

environment:
  GOPATH: c:\gopath

stack: go 1.10

platform: x64

install:
 - appveyor DownloadFile https://github.com/the-tcpdump-group/libpcap/archive/libpcap-1.9.0.zip
 - dir
 - 7z x libpcap-1.9.0.zip -olibpcap
 - dir libpcap

before_build:
 - go get ./...

# before_test:
#   - go vet ./...

# test_script:
#   - go test ./...