image:
- Visual Studio 2017
build: on

clone_folder: c:\gopath\src\github.com\adedayo\tcpscan

environment:
  GOPATH: c:\gopath

stack: go 1.10

before_build:
 - go get ./...

# before_test:
#   - go vet ./...

# test_script:
#   - go test ./...